# Generated by Django 5.1.1 on 2024-10-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='lista_tarefa',
        ),
        migrations.AddField(
            model_name='listatarefa',
            name='tarefa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tarefas.tarefa'),
        ),
    ]
