# Generated by Django 5.1.1 on 2024-10-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_tarefa_lista_tarefa_listatarefa_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listatarefa',
            name='tarefa',
        ),
        migrations.AddField(
            model_name='listatarefa',
            name='tarefas',
            field=models.ManyToManyField(null=True, to='tarefas.tarefa'),
        ),
    ]
